name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci --legacy-peer-deps

    - name: Build Backend
      working-directory: ./backend
      run: npm run build
      env:
        NODE_ENV: production

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
      env:
        NODE_ENV: production

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      if: success()

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test
      if: success()

    - name: Upload Backend Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: ./backend/dist
        if-no-files-found: error

    - name: Upload Frontend Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./frontend/dist
        if-no-files-found: error 